version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./go.mod:/service/go.mod
      - ./go.sum:/service/go.sum
      - ./src/:/service/src
